const char* kona_lua = 
" "
" "
" "
" "
"Kona = { "
"  hadError=false, "
"  hadRuntimeError=false, "
"  exit=false, "
"   "
"} "
" "
"function Kona:main(...) "
"   "
"  args = {...} "
"  if (#args > 1) then "
"    print('Usage: jlox [script]') "
"  elseif #args == 1 then "
"     "
"  else "
"    Kona:runPrompt() "
"  end "
"end "
" "
"function Kona:run(input) "
"  print(\"Trying to load a chunk\") "
"  print(input) "
"  chunk = load(input) "
"  chunk() "
"end "
" "
" "
"function Kona:runPrompt() "
"  io.write(\"start Kona Prompt:\")  "
"  io.flush() "
"  repeat "
"    io.write(\"> \")  "
"    io.flush()  "
"    input=io.read()  "
"    print(\"reading the buffer\") "
"    if not (input == \"exit\") then "
"      print(input) "
"       "
"      Kona:run(input) "
"       "
"    end "
"    print(\"after input?\") "
"  until input == \"exit\" or Kona.exit == true "
"end "
" "
"Kona_start = function() "
"  Kona:main() "
"end "
" "
" "
" "
" "
;